services:
  - type: web
    name: blood-group-fingerprint
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.9.12